language: csharp
solution: BTDMG.sln # solution parameter allows travis to automatically restore nuget packages and build the sln
dotnet: 3.1 # <- needed since we're on net core 3.1
# TODO: update to dotnet 5.0?

os:
- linux
- osx
- windows

# mono: # not needed, on net core
# - latest

script:
- dotnet restore # <- needed since we're on net core 3.1
